### ISSUE TITLE
Error when open matrix with field of plugin

### ISSUE THREAD

**Issue by some-dima** [spicywebau/craft-odds-and-ends#27] opened 2023-03-22 11:30 UTC
PHP 8.2.4
Craft Pro 4.4.5
Yii 2.0.47

Declaration of spicyweb\oddsandends\fields\Width::translatedOptions(bool $encode = false): array must be compatible with craft\fields\BaseOptionsField::translatedOptions(bool $encode = false, mixed $value = null, ?craft\base\ElementInterface $element = null): array

<img width="648" alt="image" src="https://user-images.githubusercontent.com/97662918/226891154-431819c7-189d-43b1-b87b-e3c354d5d9c8.png">

**Comment by ttempleton** [comment] 2023-03-23 02:26
Duplicate of #25

**Closed by ttempleton** 2023-03-23 02:26 UTC
